(()=>{
 const categories={all:'Все',tattoo:'Татуировки',piercing:'Пирсинг',permanent:'Перманентный макияж',training:'Обучение'},services={tattoo:'Татуировка',piercing:'Пирсинг',permanent:'Перманентный макияж',training:'Обучение'};
 const priority={tattoo:0,piercing:1,permanent:2,training:3},grid=document.querySelector('.catalog-grid'),search=document.querySelector('#catalog-search'),sort=document.querySelector('#catalog-sort'),count=document.querySelector('#catalog-count'),empty=document.querySelector('.catalog-empty'),reset=document.querySelector('#reset-filters');
 const params=new URLSearchParams(location.search);let category=Object.hasOwn(categories,params.get('category'))?params.get('category'):'all';search.value=params.get('q')||'';if(['default','price-asc','price-desc','name'].includes(params.get('sort')))sort.value=params.get('sort');
 const normalize=text=>text.toLocaleLowerCase('ru').replaceAll('ё','е').trim(),rub=value=>new Intl.NumberFormat('ru-RU').format(value)+' ₽';
 function updateUrl(){const query=new URLSearchParams();if(category!=='all')query.set('category',category);if(search.value.trim())query.set('q',search.value.trim());if(sort.value!=='default')query.set('sort',sort.value);history.replaceState(null,'',location.pathname+(query.size?'?'+query:'')+location.hash)}
 function render(){
  const directory=category==='all';document.body.classList.toggle('catalog-directory-view',directory);document.querySelector('#catalog-categories').hidden=!directory;document.querySelector('#catalog-list').hidden=directory;document.querySelector('.catalog-back').hidden=directory;
  document.querySelector('#catalog-title').textContent=directory?'ПРАЙС':categories[category].toLocaleUpperCase('ru');document.querySelector('#catalog-subtitle').textContent=directory?'Выбери направление':'Стоимость услуг и запись';const current=document.querySelector('#catalog-current');current.hidden=directory;current.textContent=directory?'':' / '+categories[category];document.title=(directory?'Прайс':categories[category])+' — Darya';
  const query=normalize(search.value);const items=catalogData.items.filter(item=>(directory||item.category===category)&&normalize(item.name).includes(query));items.sort((a,b)=>sort.value==='price-asc'?a.price-b.price:sort.value==='price-desc'?b.price-a.price:sort.value==='name'?a.name.localeCompare(b.name,'ru'):priority[a.category]-priority[b.category]||a.id.localeCompare(b.id));
  grid.innerHTML=items.map(item=>`<article class="catalog-card" data-booking data-service="${services[item.category]}" data-product="${item.name}" data-catalog-price="${rub(item.price)}" tabindex="0" role="button" aria-label="${item.name}, ${rub(item.price)}. Записаться"><div class="card-top"><span>${categories[item.category]}</span><span>${item.id}</span></div><h2>${item.name}</h2><p class="item-price">от ${rub(item.price)}</p><button class="item-details" type="button">Записаться <span class="arrow"></span></button></article>`).join('');
  count.textContent='Найдено: '+items.length;empty.hidden=items.length!==0;reset.hidden=!query&&sort.value==='default';updateUrl();
 }
 search.addEventListener('input',render);sort.addEventListener('change',render);const clear=()=>{search.value='';sort.value='default';render()};reset.addEventListener('click',clear);document.querySelector('#empty-reset').addEventListener('click',clear);
 grid.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('.catalog-card')){event.preventDefault();event.target.click()}});
 const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});const closeMenu=()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});render();
})();
